### PR TITLE
implement ValidationServiceInterface

### PR DESCRIPTION
**Pull request by haebich**
ability to decorate ValidationService

### CODE REVIEW

**Comment by mitelg** [comment]
hey @haebich,
thanks for your PR. Though it was quite intentionally that this service has no interface for decoration, my question ist why do you want to extend it? These validations are based on specifications provided directly by PayPal. If they don't match, instalments won't work.

**Comment by haebich** [comment]
@mitelg i understod. It's risky to change and could be a possible source of errors. In my case we want to set the limit up to 250. I know this could be realised via smarty or plugin config.

1. I think this kind of logic should not be in smarty templates
2. Plugin config would be a good solution but i think the interface is better for enterprise projects

**Comment by mitelg** [comment]
@haebich I see your use case there. maybe you could build a config that is only changeable programmatically, like a DIC parameter or something like that. If this doesn't fit, we could change to an interface here

**Comment by mitelg** [comment]
@haebich are you still on this?

**Comment by haebich** [comment]
@mitelg yes i'am. If i find a piece of time i will change to dic param

**Comment by mitelg** [comment]
hey @haebich 
for a better overview I would like to close the PR for now. We highly appreciate another PR, if you find the time to do the discussed points :wink: :+1: 
thanks anyway for your contribution!

**Pull request closed without merging**
